import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

const blog = defineCollection({
	loader: glob({ base: './src/content/blog', pattern: '**/*.{md,mdx}' }),
	schema: z.object({
		title: z.string(),
		description: z.string(),
		pubDate: z.coerce.date(),
		updatedDate: z.coerce.date().optional(),
		draft: z.boolean().optional(),
		heroAscii: z.string().optional(),
		// Social share image (Open Graph / Twitter). Must be 1200x630 to match
		// the declared card dimensions; generated by scripts/generate-og.mjs.
		image: z.string().optional(),
	}),
});

export const collections = { blog };
